[workspace]
members = ["bevy_spacetimedb", "macros"]
resolver = "3"

[workspace.dependencies]
bevy = { version = "0.18", default-features = false, features = [
    "std",
    "bevy_log",
] }
spacetimedb-sdk = { version = "1.12.0" }
